### ISSUE TITLE
'Maximum function nesting level of 100 reached' after load

### ISSUE THREAD

**Issue by myfakeusername** [Waavi/translation#24] opened 2014-09-08 12:44 UTC
I have this error when I run translator:load

'Maximum function nesting level of 100 reached'

I even changed the max nesting to 1000 but I still have the error.

Any ideas what I can do?

**Comment by bytestream** [comment] 2015-03-24 22:30
The issue is in the composer dependency "waavi/model", see: https://github.com/Waavi/model

If you look at line 251 in ````vendor\waavi\model\src\Waavi\Model\WaaviModel.php```` and step through the code you find that $this->getQualifiedDeletedAtColumn() calls line 3102 in ````vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php```` which calls $this->newQuery again and again...

Laravel 4.2 adds traits for soft-deleting which is the cause of the problem so adding ````use SoftDeletingTrait;```` to the top of ````vendor\waavi\model\src\Waavi\Model\WaaviModel.php```` should fix the problem.

**Comment by sildraug** [comment] 2015-12-07 14:22
This should be fixed in our latest release for Laravel 5.

**Closed by sildraug** 2015-12-07 14:22 UTC
